import { HousingLocation } from "./housing-location";

export const HousingLocationData: HousingLocation[] = [
 {
    id: 1,
    name: 'Marhaba Residences',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    address: '123 Rue des Roses, Casablanca',
    longitude: -7.61053238109,
    latitude: 33.560439524998,
    photo: '../assets/residence-1.jpg',
    availableUnits: 3,
    wifi: true,
    laundry: true
  },
  {
    id: 2,
    name: 'Majestic Mansions',
    city: 'Rabat',
    state: 'Rabat-Salé-Kénitra',
    address: '456 Avenue Mohammed V, Rabat',
    longitude: -6.836820,
    latitude: 34.022405,
    photo: '../assets/residence-1.jpg',
    availableUnits: 2,
    wifi: true,
    laundry: false
  },
  {
    id: 3,
    name: 'Atlas Apartments',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    address: '789 Boulevard Hassan II, Marrakech',
    longitude: -7.986197,
    latitude: 31.629472,
    photo: '../assets/residence-2.jpg',
    availableUnits: 5,
    wifi: true,
    laundry: true
  },
  {
    id: 4,
    name: 'Sahara Suites',
    city: 'Agadir',
    state: 'Souss-Massa',
    address: '1010 Avenue du Founty, Agadir',
    longitude: -9.609768,
    latitude: 30.421089,
    photo: '../assets/residence-3.jpg',
    availableUnits: 1,
    wifi: false,
    laundry: true
  },
  {
    id: 5,
    name: 'Royal Residency',
    city: 'Fes',
    state: 'Fes-Meknès',
    address: '222 Rue de la Kasbah, Fes',
    longitude: -4.978684,
    latitude: 34.073237,
    photo: '../assets/residence-4.webp',
    availableUnits: 4,
    wifi: true,
    laundry: true
  },
  {
    id: 6,
    name: 'Golden Gate Apartments',
    city: 'Tangier',
    state: 'Tanger-Tetouan-Al Hoceima',
    address: '333 Avenue Mohammed VI, Tangier',
    longitude: -5.816345,
    latitude: 35.767192,
    photo: '../assets/residence-5.jpg',
    availableUnits: 0,
    wifi: true,
    laundry: false
  },
  {
    id: 7,
    name: 'Oasis Towers',
    city: 'Meknes',
    state: 'Fes-Meknes',
    address: '444 Avenue Allal Ben Abdellah, Meknes',
    longitude: -5.557424,
    latitude: 33.897496,
    photo: '../assets/residence-6.webp',
    availableUnits: 2,
    wifi: true,
    laundry: true
  },
  {
    id: 8,
    name: 'Dreamland Residences',
    city: 'Essaouira',
    state: 'Marrakech-Safi',
    address: '555 Rue du Marché, Essaouira',
    longitude: -9.767868,
    latitude: 31.513031,
    photo: '../assets/residence-7.jpg',
    availableUnits: 3,
    wifi: true,
    laundry: false
  },
  {
    id: 9,
    name: 'Palm Palace',
    city: 'Ouarzazate',
    state: 'Drâa-Tafilalet',
    address: '666 Avenue Mohammed V, Ouarzazate',
    longitude: -6.909432,
    latitude: 30.921686,
    photo: '../assets/residence-8.jpg',
    availableUnits: 1,
    wifi: true,
    laundry: true
  }
]
